[package]
name = "mos6502-emulator"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield-struct = "0.11.0"
thiserror = "2.0.16"

[dev-dependencies]
mockall = "0.13.1"
