name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      # Make sure CI fails on all warnings, including Clippy lints
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Show rust toolchain info
        shell: bash
        run: |
          rustup -V
          rustup default
          cargo -V
          rustc -V

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      - name: Lint
        run: |
          cargo clippy --all-targets --all-features -- -v

      - uses: DavidAnson/markdownlint-cli2-action@v12
        name: Markdown linter
        with:
          globs: '**/*.md'

  build-test:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    env:
      # Make sure CI fails on all warnings, including Clippy lints
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build
        run: cargo build --workspace --all-targets --all-features --verbose

      - name: Test
        run: cargo test --all-targets --all-features
