name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest
    env:
      # Make sure CI fails on all warnings, including Clippy lints
      RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Show rust toolchain info
        shell: bash
        run: |
          rustup -V
          rustup default
          cargo -V
          rustc -V

      - name: Build
        run: cargo build --workspace

      - name: Test
        run: cargo test --all-targets --all-features

      - name: Check
        run: |
          cargo clippy --all-targets --all-features
          cargo fmt --all -- --check
